version: '2'
services:
  api:
    build: ./api        
    ports:
      - "8008:8008"
    volumes:
      - ./api:/api
    command: bash -c "python manage.py runserver 0.0.0.0:8008"

  web:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
